// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securities.proto

package ru.sbrf.efx.zeromqtest.dto;

public final class Securities {
  private Securities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SecurityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Security)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string secId = 2;</code>
     * @return The secId.
     */
    java.lang.String getSecId();
    /**
     * <code>string secId = 2;</code>
     * @return The bytes for secId.
     */
    com.google.protobuf.ByteString
        getSecIdBytes();

    /**
     * <code>double rate = 3;</code>
     * @return The rate.
     */
    double getRate();
  }
  /**
   * Protobuf type {@code protobuf.Security}
   */
  public static final class Security extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Security)
      SecurityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Security.newBuilder() to construct.
    private Security(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Security() {
      secId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Security();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Security(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              secId_ = s;
              break;
            }
            case 25: {

              rate_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sbrf.efx.zeromqtest.dto.Securities.internal_static_protobuf_Security_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sbrf.efx.zeromqtest.dto.Securities.internal_static_protobuf_Security_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sbrf.efx.zeromqtest.dto.Securities.Security.class, ru.sbrf.efx.zeromqtest.dto.Securities.Security.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int SECID_FIELD_NUMBER = 2;
    private volatile java.lang.Object secId_;
    /**
     * <code>string secId = 2;</code>
     * @return The secId.
     */
    @java.lang.Override
    public java.lang.String getSecId() {
      java.lang.Object ref = secId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secId_ = s;
        return s;
      }
    }
    /**
     * <code>string secId = 2;</code>
     * @return The bytes for secId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecIdBytes() {
      java.lang.Object ref = secId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RATE_FIELD_NUMBER = 3;
    private double rate_;
    /**
     * <code>double rate = 3;</code>
     * @return The rate.
     */
    @java.lang.Override
    public double getRate() {
      return rate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secId_);
      }
      if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
        output.writeDouble(3, rate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(secId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secId_);
      }
      if (java.lang.Double.doubleToRawLongBits(rate_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.sbrf.efx.zeromqtest.dto.Securities.Security)) {
        return super.equals(obj);
      }
      ru.sbrf.efx.zeromqtest.dto.Securities.Security other = (ru.sbrf.efx.zeromqtest.dto.Securities.Security) obj;

      if (getId()
          != other.getId()) return false;
      if (!getSecId()
          .equals(other.getSecId())) return false;
      if (java.lang.Double.doubleToLongBits(getRate())
          != java.lang.Double.doubleToLongBits(
              other.getRate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SECID_FIELD_NUMBER;
      hash = (53 * hash) + getSecId().hashCode();
      hash = (37 * hash) + RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.sbrf.efx.zeromqtest.dto.Securities.Security prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Security}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Security)
        ru.sbrf.efx.zeromqtest.dto.Securities.SecurityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.sbrf.efx.zeromqtest.dto.Securities.internal_static_protobuf_Security_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.sbrf.efx.zeromqtest.dto.Securities.internal_static_protobuf_Security_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.sbrf.efx.zeromqtest.dto.Securities.Security.class, ru.sbrf.efx.zeromqtest.dto.Securities.Security.Builder.class);
      }

      // Construct using ru.sbrf.efx.zeromqtest.dto.Securities.Security.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        secId_ = "";

        rate_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.sbrf.efx.zeromqtest.dto.Securities.internal_static_protobuf_Security_descriptor;
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Securities.Security getDefaultInstanceForType() {
        return ru.sbrf.efx.zeromqtest.dto.Securities.Security.getDefaultInstance();
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Securities.Security build() {
        ru.sbrf.efx.zeromqtest.dto.Securities.Security result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Securities.Security buildPartial() {
        ru.sbrf.efx.zeromqtest.dto.Securities.Security result = new ru.sbrf.efx.zeromqtest.dto.Securities.Security(this);
        result.id_ = id_;
        result.secId_ = secId_;
        result.rate_ = rate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.sbrf.efx.zeromqtest.dto.Securities.Security) {
          return mergeFrom((ru.sbrf.efx.zeromqtest.dto.Securities.Security)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.sbrf.efx.zeromqtest.dto.Securities.Security other) {
        if (other == ru.sbrf.efx.zeromqtest.dto.Securities.Security.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getSecId().isEmpty()) {
          secId_ = other.secId_;
          onChanged();
        }
        if (other.getRate() != 0D) {
          setRate(other.getRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.sbrf.efx.zeromqtest.dto.Securities.Security parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.sbrf.efx.zeromqtest.dto.Securities.Security) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object secId_ = "";
      /**
       * <code>string secId = 2;</code>
       * @return The secId.
       */
      public java.lang.String getSecId() {
        java.lang.Object ref = secId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string secId = 2;</code>
       * @return The bytes for secId.
       */
      public com.google.protobuf.ByteString
          getSecIdBytes() {
        java.lang.Object ref = secId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string secId = 2;</code>
       * @param value The secId to set.
       * @return This builder for chaining.
       */
      public Builder setSecId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string secId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecId() {
        
        secId_ = getDefaultInstance().getSecId();
        onChanged();
        return this;
      }
      /**
       * <code>string secId = 2;</code>
       * @param value The bytes for secId to set.
       * @return This builder for chaining.
       */
      public Builder setSecIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secId_ = value;
        onChanged();
        return this;
      }

      private double rate_ ;
      /**
       * <code>double rate = 3;</code>
       * @return The rate.
       */
      @java.lang.Override
      public double getRate() {
        return rate_;
      }
      /**
       * <code>double rate = 3;</code>
       * @param value The rate to set.
       * @return This builder for chaining.
       */
      public Builder setRate(double value) {
        
        rate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRate() {
        
        rate_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Security)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Security)
    private static final ru.sbrf.efx.zeromqtest.dto.Securities.Security DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.sbrf.efx.zeromqtest.dto.Securities.Security();
    }

    public static ru.sbrf.efx.zeromqtest.dto.Securities.Security getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Security>
        PARSER = new com.google.protobuf.AbstractParser<Security>() {
      @java.lang.Override
      public Security parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Security(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Security> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Security> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.sbrf.efx.zeromqtest.dto.Securities.Security getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Security_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Security_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020securities.proto\022\010protobuf\"3\n\010Security" +
      "\022\n\n\002id\030\001 \001(\005\022\r\n\005secId\030\002 \001(\t\022\014\n\004rate\030\003 \001(" +
      "\001B(\n\032ru.sbrf.efx.zeromqtest.dtoB\nSecurit" +
      "iesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_Security_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Security_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Security_descriptor,
        new java.lang.String[] { "Id", "SecId", "Rate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
