// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscribes.proto

package ru.sbrf.efx.zeromqtest.dto;

public final class Subscribes {
  private Subscribes() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protobuf.Subscribe)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string serviceName = 2;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 2;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
    getServiceNameBytes();

    /**
     * <code>string topicName = 3;</code>
     * @return The topicName.
     */
    java.lang.String getTopicName();
    /**
     * <code>string topicName = 3;</code>
     * @return The bytes for topicName.
     */
    com.google.protobuf.ByteString
    getTopicNameBytes();
  }
  /**
   * Protobuf type {@code protobuf.Subscribe}
   */
  public static final class Subscribe extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:protobuf.Subscribe)
          SubscribeOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Subscribe.newBuilder() to construct.
    private Subscribe(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscribe() {
      serviceName_ = "";
      topicName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Subscribe();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subscribe(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serviceName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              topicName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return ru.sbrf.efx.zeromqtest.dto.Subscribes.internal_static_protobuf_Subscribe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return ru.sbrf.efx.zeromqtest.dto.Subscribes.internal_static_protobuf_Subscribe_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.class, ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int SERVICENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object serviceName_;
    /**
     * <code>string serviceName = 2;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 2;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPICNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object topicName_;
    /**
     * <code>string topicName = 3;</code>
     * @return The topicName.
     */
    @java.lang.Override
    public java.lang.String getTopicName() {
      java.lang.Object ref = topicName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      }
    }
    /**
     * <code>string topicName = 3;</code>
     * @return The bytes for topicName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topicName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topicName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topicName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe)) {
        return super.equals(obj);
      }
      ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe other = (ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe) obj;

      if (getId()
              != other.getId()) return false;
      if (!getServiceName()
              .equals(other.getServiceName())) return false;
      if (!getTopicName()
              .equals(other.getTopicName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + TOPICNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTopicName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Subscribe}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protobuf.Subscribe)
            ru.sbrf.efx.zeromqtest.dto.Subscribes.SubscribeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return ru.sbrf.efx.zeromqtest.dto.Subscribes.internal_static_protobuf_Subscribe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return ru.sbrf.efx.zeromqtest.dto.Subscribes.internal_static_protobuf_Subscribe_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.class, ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.Builder.class);
      }

      // Construct using ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        serviceName_ = "";

        topicName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return ru.sbrf.efx.zeromqtest.dto.Subscribes.internal_static_protobuf_Subscribe_descriptor;
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe getDefaultInstanceForType() {
        return ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.getDefaultInstance();
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe build() {
        ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe buildPartial() {
        ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe result = new ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe(this);
        result.id_ = id_;
        result.serviceName_ = serviceName_;
        result.topicName_ = topicName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe) {
          return mergeFrom((ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe other) {
        if (other == ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (!other.getTopicName().isEmpty()) {
          topicName_ = other.topicName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 2;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
      getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 2;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {

        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 2;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        serviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topicName_ = "";
      /**
       * <code>string topicName = 3;</code>
       * @return The topicName.
       */
      public java.lang.String getTopicName() {
        java.lang.Object ref = topicName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topicName = 3;</code>
       * @return The bytes for topicName.
       */
      public com.google.protobuf.ByteString
      getTopicNameBytes() {
        java.lang.Object ref = topicName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          topicName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topicName = 3;</code>
       * @param value The topicName to set.
       * @return This builder for chaining.
       */
      public Builder setTopicName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        topicName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopicName() {

        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      /**
       * <code>string topicName = 3;</code>
       * @param value The bytes for topicName to set.
       * @return This builder for chaining.
       */
      public Builder setTopicNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        topicName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Subscribe)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Subscribe)
    private static final ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe();
    }

    public static ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscribe>
            PARSER = new com.google.protobuf.AbstractParser<Subscribe>() {
      @java.lang.Override
      public Subscribe parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscribe(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subscribe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscribe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.sbrf.efx.zeromqtest.dto.Subscribes.Subscribe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protobuf_Subscribe_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_protobuf_Subscribe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\020subscribes.proto\022\010protobuf\"?\n\tSubscrib" +
                    "e\022\n\n\002id\030\001 \001(\005\022\023\n\013serviceName\030\002 \001(\t\022\021\n\tto" +
                    "picName\030\003 \001(\tB(\n\032ru.sbrf.efx.zeromqtest." +
                    "dtoB\nSubscribesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    });
    internal_static_protobuf_Subscribe_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Subscribe_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_protobuf_Subscribe_descriptor,
            new java.lang.String[] { "Id", "ServiceName", "TopicName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
